version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mh_facilities
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - mhnet

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mh_facilities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mhnet

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - mhnet
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro

networks:
  mhnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
