name: Deploy Frontend — MH Facilities

on:
  push:
    branches:
      - main
    paths:
      - "mh-facilities/frontend/**"

  workflow_dispatch:

jobs:
  deploy:
    name: Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy para Vercel
        run: npx vercel deploy --prod --token "${{ secrets.VERCEL_TOKEN }}" --yes --scope nicolasnick2903-stacks-projects
        working-directory: mh-facilities/frontend
